# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 2Devs1Stack
email:
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on software development process and technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://2devs1stack.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: 2devs1stack

# Build settings
markdown: kramdown
